[package]
name = "macros"
version = "0.1.0"
authors = ["Gustav Eiman <gustav.eiman@oneagency.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.41"
quote = "1.0.7"

[lib]
proc-macro = true